#!/bin/bash

source $(dirname $0)/utils.sh

if [ ! -n "$1" ] ;then
    echo "please input pod name to restart"
    exit 1
fi
IFS=$'\n'
pods=(`kubectl -n $NS get po | grep $1`)
[[ ${#pods[@]} == 0 ]] && echo "pod not found" && exit 1
echo ""
del_pods=""
for pod in ${pods[@]}; do
    echo $"${pod}"
    podname=`echo $pod | cut -d ' ' -f1`
    del_pods="$del_pods $podname";
done
unset IFS
  
echo ""
echo "will delete these pods:$del_pods, and then k8s will recreate them."

read -p "Are you sure you want to continue? Enter [Y/N]: " confirm
  
[ -z "${confirm}" -o "${confirm}" = "Y" -o "${confirm}" = "y" ] && kubectl -n $NS delete po $del_pods
echo "now pod info: "
kubectl -n $NS get po | grep $1