apiVersion: v1
kind: Pod
metadata:
  name: db-backup
  namespace: "qtsa"
spec:
  nodeSelector:
    "kubernetes.io/hostname": "node4"
  terminationGracePeriodSeconds: 10
  serviceAccountName: "titan-sa"
  containers:
    - name: db-backup
      imagePullPolicy: IfNotPresent
      image: "registry.qingteng.cn/titan-container/dbbackup:3.4.0-1"
      resources:
        limits:
          memory: "10240Mi"
          cpu: "8"
        requests:
          cpu: "0.5"
          memory: "512Mi"
      ports:
        - name: mongos
          protocol: TCP
          containerPort: 27017
      command: ["mongos", "--config", "/etc/mongo/mongos.conf", "--keyFile", "/etc/mongo/keyfile"]
      readinessProbe:
        tcpSocket:
          port: 27017
        initialDelaySeconds: 10
        timeoutSeconds: 5
        failureThreshold: 5
      livenessProbe:
        tcpSocket:
          port: 27017
        timeoutSeconds: 5
      volumeMounts:
        - name: mongo-temp
          mountPath: "/data/mongo-temp"
        - name: config
          mountPath: /etc/mongo
  initContainers:
    - name: configmap-copy
      image: "registry.qingteng.cn/titan-container/alpine:3.12"
      imagePullPolicy: IfNotPresent
      command:
      - sh
      - -c
      - cp -f /etc/mongo-temp/* /etc/mongo/ && chmod 600 /etc/mongo/keyfile
      volumeMounts:
        - name: mongo-config
          mountPath: /etc/mongo-temp/
        - name: config
          mountPath: /etc/mongo
  volumes:
    - name: mongo-temp
      hostPath:
        path: /data/mongo-temp
        type: DirectoryOrCreate
    - name: mongo-config
      configMap:
        name: mongo-configmap
        items:
        - key: keyfile
          path: keyfile
        - key: mongos.conf
          path: mongos.conf
    - name: config
      emptyDir: {}
