FROM registry.qingteng.cn/titan-container/ubuntu:focal-20220302

RUN sed -i 's/ports.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && sed -i 's/archive.ubuntu.com/cn.archive.ubuntu.com/g' /etc/apt/sources.list \
    && apt-get update && apt install -y --no-install-recommends python3 python3-pip wget vim && apt clean && rm -rf /var/lib/apt/lists/* && echo ':set encoding=utf-8' >> /etc/vim/vimrc

ARG VERSION=2.12.1
RUN pip3 install --no-cache-dir --no-compile "ansible-core==2.12.1" -i https://mirrors.aliyun.com/pypi/simple/;

ENV LANG en_US.UTF-8
