---
- hosts: master[0]
  gather_facts: false
  tasks:
    - name:
      include_role:
        name: reset
        tasks_from: remove_registry.yml

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: reset
