---
- hosts: k3s_cluster
  remote_user: root
  gather_facts: yes
  tasks:
  - name: test4
    shell: echo "{{ ansible_hostname }}" >> /tmp/ansible_hostname_list1.txt
    delegate_to: localhost

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
  - set_fact:
      p: "{{ lookup('file', '/tmp/ansible_hostname_list1.txt').splitlines() }}"
  - debug: msg={{ p }}
  
  - debug: msg={{ p | unique }}
  
  - debug: msg={{ p | difference(p | unique)| length }}
