#!/bin/bash
#
# logstash  qingteng logstash logstash
#
# Author:       leilei.zhai < leilei.zhai@qingteng.cn >
#
# chkconfig:	- 95 95
#
# description:  qingteng-logstash
#
# processname:  logstash
#
# source function library
. /etc/rc.d/init.d/functions

DIR_BIN=/usr/share/logstash/bin/logstash
LOG=/data/titan-logs/logstash/logstash_start.log
PIDFILE=/data/titan-logs/logstash/logstash.pid
DATA_DIR=/data/logstash/
CONF_DIR=/usr/local/qingteng/logstash
RETVAL=0
LOGSTASH_PATH=/usr/local/qingteng/logstash/logstash

if [ -f "$LOGSTASH_PATH" ]; then
    . "$LOGSTASH_PATH"
fi


getpid(){
    pgrep -f logstash
}

start() {
	echo -n $"Starting logstash: "
	daemon --user logstash --pidfile=${PIDFILE} "nohup /usr/share/logstash/bin/logstash --path.settings $CONF_DIR >$LOG 2>&1 &"
	RETVAL=$?
	echo
        sleep 3
        ppid=`getpid`
        [ "$ppid" != "" ] && echo $ppid >$PIDFILE
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/logstash
}

stop() {
    echo -n $"Stopping logstash: "
    killproc -p ${PIDFILE} logstash
    pgrep -f logstash | xargs kill -9
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/logstash && success || failure
}

rh_status() {
    status -p $PIDFILE logstash
}


restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  status)
	rh_status
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
	exit 1
esac

exit $RETVAL
